// The golden co-authoring task set (~20 tasks; see verifier/PLAN.md §Step 3). Instructions
// double as the phase-2 AI prompts; ops are the deterministic stand-in. xfail pins on the
// #83 id class mirror verifier/expectations.ts.
import type { GoldenTask } from "./types";

const C = "tests/e2e/corpus";
const ID_DROP = "#83: engine drops id on modeled nodes";

export const TASKS: GoldenTask[] = [
  { id: "cell-edit-basic", title: "rewrite one table cell", source: `${C}/schema/table.html`,
    instruction: "In the comparison table, change the Cons cell 'cost' to 'licence cost'.",
    op: { kind: "replaceText", find: "cost", replace: "licence cost" },
    expect: [{ kind: "savedContains", text: "licence cost" }, { kind: "tableDims", rows: 2, cols: 2 }, { kind: "savedContains", text: "fast" }] },
  { id: "cell-edit-numeric", title: "change a numeric cell", source: `${C}/identity/ids-mixed.html`,
    instruction: "Update the eu-west p99 from 184 to 121.",
    op: { kind: "replaceText", find: "184", replace: "121" },
    expect: [{ kind: "savedContains", text: "121" }, { kind: "savedNotContains", text: "184" }, { kind: "savedContains", text: "eu-west" }],
    expectFail: { checks: ["ids"], reason: ID_DROP, issue: "#83" } },
  { id: "prose-bold-range", title: "bold a phrase", source: `${C}/schema/marks-soup.html`,
    instruction: "Bold the word 'loose' in the badge line.",
    op: { kind: "wrapMark", find: "loose", mark: "bold" },
    expect: [{ kind: "markPreserved", find: "loose", mark: "bold" }] },
  { id: "prose-rewrite-across-marks", title: "rewrite across marks", source: `${C}/schema/marks-soup.html`,
    instruction: "Replace the word 'emphasis' with 'stress' without disturbing surrounding formatting or the link.",
    op: { kind: "replaceText", find: "emphasis", replace: "stress" },
    expect: [{ kind: "savedContains", text: "stress" }, { kind: "savedContains", text: "https://x.example" }] },
  { id: "prose-edit-classed-heading", title: "reword a classed heading", source: `${C}/styling-source/class-and-style.html`,
    instruction: "Retitle the 'Background' section to 'Founding story'.",
    op: { kind: "replaceText", find: "Background", replace: "Founding story" },
    expect: [{ kind: "nodeText", match: { type: "heading" }, equals: "Founding story" }, { kind: "savedContains", text: 'class="card"' }] },
  { id: "inline-style-color-change", title: "change a text color (contrast-gated)", source: `${C}/identity/deco-dots.html`,
    instruction: "Set 'drained hourly' in dark slate so it stands out — and keep it readable (AA).",
    op: { kind: "wrapMark", find: "drained hourly", mark: "textStyle", attrs: { color: "#1f2937" } },
    contrastGate: true,
    expect: [{ kind: "savedContains", text: "#1f2937" }],
    expectFail: { checks: ["ids"], reason: ID_DROP, issue: "#83" } },
  { id: "styled-span-heavy-edit", title: "edit text beside a styled span", source: `${C}/schema/marks-soup.html`,
    instruction: "Change 'line' to 'row' in the badge line without disturbing the tag span.",
    op: { kind: "replaceText", find: " line.", replace: " row." },
    expect: [{ kind: "savedContains", text: " row." }, { kind: "savedContains", text: 'class="tag"' }, { kind: "countNodes", type: "styledSpan", equals: 1 }] },
  { id: "deco-span-survival", title: "edit beside decorative dots", source: `${C}/identity/deco-dots.html`,
    instruction: "Change 'backlog above normal' to 'backlog clearing'.",
    op: { kind: "replaceText", find: "backlog above normal", replace: "backlog clearing" },
    expect: [{ kind: "savedContains", text: "backlog clearing" }, { kind: "countNodes", type: "decoSpan", equals: 3 }],
    expectFail: { checks: ["ids"], reason: ID_DROP, issue: "#83" } },
  { id: "block-insert-para", title: "insert a paragraph after a heading", source: `${C}/identity/anchors-toc.html`,
    instruction: "Add a one-line summary sentence right after the Results heading.",
    op: { kind: "insertBlock", after: { type: "heading", textContains: "Results" }, html: "<p>Net: a quiet but solid quarter.</p>" },
    expect: [{ kind: "savedContains", text: "quiet but solid quarter" }, { kind: "savedContains", text: "Gross margin" }],
    expectFail: { checks: ["ids"], reason: ID_DROP, issue: "#83" } },
  { id: "block-delete-section", title: "delete one section body", source: `${C}/identity/anchors-toc.html`,
    instruction: "Remove the Appendix body paragraph (keep the heading).",
    op: { kind: "deleteBlock", match: { type: "paragraph", textContains: "data room" } },
    expect: [{ kind: "savedNotContains", text: "data room" }, { kind: "savedContains", text: "Appendix" }],
    expectFail: { checks: ["ids"], reason: ID_DROP, issue: "#83" } },
  { id: "block-move-up", title: "move a block above its predecessor", source: `${C}/identity/deco-dots.html`,
    instruction: "Move the Batch status line above the Queue line.",
    op: { kind: "moveBlock", match: { type: "paragraph", textContains: "Batch" }, to: "before", anchor: { type: "paragraph", textContains: "Queue" } },
    expect: [{ kind: "savedContains", text: "Batch" }, { kind: "savedContains", text: "Queue" }],
    expectFail: { checks: ["ids"], reason: ID_DROP, issue: "#83" } },
  { id: "multi-block-restructure", title: "retitle + edit two spots", source: `${C}/identity/ids-mixed.html`,
    instruction: "Retitle 'Service metrics' to 'Reliability metrics' and note the review is closed.",
    op: { kind: "sequence", ops: [
      { kind: "replaceText", find: "Service metrics", replace: "Reliability metrics" },
      { kind: "replaceText", find: "incident review", replace: "closed incident review" },
    ] },
    expect: [{ kind: "savedContains", text: "Reliability metrics" }, { kind: "savedContains", text: "closed incident review" }],
    expectFail: { checks: ["ids"], reason: ID_DROP, issue: "#83" } },
  { id: "table-sort-desc", title: "sort table rows (scripted)", source: `${C}/schema/table.html`,
    instruction: "Sort the comparison table's body rows by the first column descending.",
    op: { kind: "sortTable", match: { type: "table" }, column: 0, order: "desc" },
    expect: [{ kind: "tableDims", rows: 2, cols: 2 }, { kind: "savedContains", text: "fast" }] },
  { id: "list-task-add", title: "append a list item", source: `${C}/schema/lists.html`,
    instruction: "Add 'ship the retro notes' to the end of the first list.",
    op: { kind: "insertBlock", after: { type: "bulletList" }, html: "<p>ship the retro notes</p>" },
    expect: [{ kind: "savedContains", text: "ship the retro notes" }] },
  { id: "callout-kind-change", title: "flip a callout info→warn", source: "verifier/golden/fixtures/callout-clock.html",
    instruction: "Turn the deploy-freeze callout into a warning.",
    op: { kind: "setNodeAttr", match: { type: "callout" }, attrs: { kind: "warn" } },
    expect: [{ kind: "nodeAttr", match: { type: "callout" }, attr: "kind", equals: "warn" }, { kind: "savedContains", text: 'data-kind="warn"' }, { kind: "savedContains", text: "Deploy freeze" }] },
  { id: "clock-tz-edit", title: "change the clock timezone", source: "verifier/golden/fixtures/callout-clock.html",
    instruction: "Switch the office clock to New York time.",
    op: { kind: "setNodeAttr", match: { type: "clockBlock" }, attrs: { tz: "America/New_York" } },
    expect: [{ kind: "savedContains", text: 'data-tz="America/New_York"' }] },
  { id: "frozen-block-untouched", title: "edit prose beside a frozen svg", source: `${C}/identity/ids-mixed.html`,
    instruction: "Change 'every region' to 'each region'; leave the sparkline alone.",
    op: { kind: "replaceText", find: "every region", replace: "each region" },
    expect: [{ kind: "savedContains", text: "each region" }, { kind: "byteIdenticalRegion", selector: "svg" }],
    expectFail: { checks: ["ids"], reason: ID_DROP, issue: "#83" } },
  { id: "script-preservation-edit", title: "edit prose in a script-bearing doc", source: `${C}/security/script.html`,
    instruction: "Change 'shows content' to 'demonstrates content'; the doc's own script must survive byte-identical (own-files model).",
    op: { kind: "replaceText", find: "shows content", replace: "demonstrates content" },
    expect: [{ kind: "savedContains", text: "demonstrates content" }, { kind: "byteIdenticalRegion", selector: "script" }] },
  { id: "id-anchor-critical", title: "edit inside an anchored section", source: `${C}/identity/anchors-toc.html`,
    instruction: "Reword the lead paragraph under Summary.",
    op: { kind: "replaceText", find: "held steady", replace: "held firm" },
    expect: [{ kind: "savedContains", text: "held firm" }],
    expectFail: { checks: ["ids"], reason: ID_DROP + " — sec ids + TOC anchors lost", issue: "#83" } },
  { id: "id-delete-one-keep-rest", title: "delete one identified section", source: `${C}/identity/anchors-toc.html`,
    instruction: "Delete the Appendix section heading entirely.",
    op: { kind: "deleteBlock", match: { type: "heading", textContains: "Appendix" } },
    deletes: ["sec-3"],
    expect: [{ kind: "savedNotContains", text: "Appendix</h2>" }, { kind: "savedContains", text: "Results" }],
    expectFail: { checks: ["ids"], reason: ID_DROP + " — today siblings drop too, not just the deleted sec-3", issue: "#83" } },
  { id: "head-template-integrity", title: "small edit, shell byte-identical", source: `${C}/real-published/adamw.html`,
    instruction: "Fix one word; the <head>, styles and meta must not change.",
    op: { kind: "replaceText", find: "intuition", replace: "core intuition" },
    expect: [{ kind: "savedContains", text: "core intuition" }, { kind: "byteIdenticalRegion", selector: "head" }] },
  { id: "classed-heading-class-survives", title: "element CSS keeps matching after a heading edit", source: `${C}/styling-source/element-selectors.html`,
    instruction: "Retitle 'Section' to 'Overview'; the h2/b element styles must keep applying.",
    op: { kind: "replaceText", find: "Section", replace: "Overview" },
    expect: [{ kind: "savedContains", text: ">Overview<" }, { kind: "savedContains", text: "element-styled" }] },
];
